# Generated by Django 4.0.1 on 2022-02-22 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('isbn', models.CharField(db_column='isbn', max_length=13, primary_key=True, serialize=False, verbose_name='isbn')),
                ('title', models.CharField(db_column='title', max_length=50, verbose_name='kitap adı')),
                ('writer', models.CharField(db_column='writer', max_length=50, verbose_name='yazar')),
                ('genre', models.CharField(db_column='genre', max_length=20, verbose_name='tür')),
                ('publisher', models.CharField(db_column='publisher', max_length=20, verbose_name='yayıncı')),
                ('publish_year', models.IntegerField(db_column='publish_year', verbose_name='yayın yılı')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_num', models.CharField(max_length=10, verbose_name='Okul Numarası')),
                ('name', models.CharField(max_length=50)),
                ('grade', models.IntegerField()),
                ('department', models.CharField(max_length=5)),
                ('books_lended', models.IntegerField(default=0)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.unit')),
            ],
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=1)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.book')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.unit')),
            ],
        ),
        migrations.CreateModel(
            name='Lending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lend_date', models.DateField()),
                ('back_date', models.DateField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.book')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.reader')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.unit')),
            ],
        ),
        migrations.AddConstraint(
            model_name='reader',
            constraint=models.UniqueConstraint(fields=('unit', 'school_num'), name='reader_id'),
        ),
    ]
