# Generated by Django 4.0.1 on 2022-03-11 08:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('isbn', models.CharField(max_length=13, primary_key=True, serialize=False, verbose_name='isbn')),
                ('title', models.CharField(max_length=50, verbose_name='kitap adı')),
                ('writer', models.CharField(max_length=50, verbose_name='yazar')),
                ('genre', models.CharField(max_length=20, verbose_name='tür')),
                ('publisher', models.CharField(max_length=20, verbose_name='yayıncı')),
                ('publish_year', models.IntegerField(verbose_name='yayın yılı')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('school_num', models.CharField(max_length=10, verbose_name='Okul Numarası')),
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('grade', models.IntegerField()),
                ('department', models.CharField(max_length=5)),
                ('books_lended', models.IntegerField(default=0)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.unit')),
            ],
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=1)),
                ('description', models.CharField(default='', max_length=100)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.book')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.unit')),
            ],
        ),
        migrations.CreateModel(
            name='Lending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lend_date', models.DateField()),
                ('back_date', models.DateField()),
                ('returned', models.BooleanField(default=False)),
                ('library_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.library')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.reader')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.unit')),
            ],
        ),
    ]
