# Generated by Django 4.0.1 on 2022-03-07 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lending',
            name='returned',
            field=models.BooleanField(default=False),
        ),
    ]
