# Generated by Django 4.0.1 on 2022-02-23 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='reader',
            name='reader_id',
        ),
        migrations.AlterField(
            model_name='reader',
            name='id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
