# Generated by Django 4.0.1 on 2022-03-16 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='on_lending',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reader',
            name='books_on',
            field=models.IntegerField(default=0),
        ),
    ]
