# Generated by Django 4.0.1 on 2022-04-21 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_library_on_lending_reader_books_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pages',
            field=models.IntegerField(blank=True, default=150, verbose_name='Sayfa Sayısı'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reader',
            name='books_lended',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='reader',
            name='books_on',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='reader',
            name='department',
            field=models.CharField(max_length=5, verbose_name='Şube'),
        ),
        migrations.AlterField(
            model_name='reader',
            name='grade',
            field=models.IntegerField(verbose_name='Sınıf'),
        ),
        migrations.AlterField(
            model_name='reader',
            name='name',
            field=models.CharField(max_length=50, verbose_name='İsim'),
        ),
    ]
