# Generated by Django 4.0.1 on 2022-02-23 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_remove_reader_reader_id_alter_reader_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='description',
            field=models.CharField(default='', max_length=100),
        ),
    ]
