# Generated by Django 4.0.1 on 2022-06-14 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_book_pages_alter_reader_books_lended_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='provincy',
            field=models.CharField(default='Niğde', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reader',
            name='books_lended',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reader',
            name='books_on',
            field=models.IntegerField(default=0),
        ),
    ]
